spring.datasource.url=jdbc:postgresql://localhost:5432/sgs_db
spring.datasource.username=sgs_user
spring.datasource.password=sgs_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

spring.web.cors.allowed-origins=http://localhost:3000,http://127.0.0.1:5500
